### ISSUE TITLE
XML to MDMI Import Error

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#117]
Same problam as before - can't figure fix. Import generates, but is cropped at first container. XML and MDMI files attached.
[XMLtoMDMI4.20.zip](https://github.com/MDMI/mdmiecore/files/1932416/XMLtoMDMI4.20.zip)

**Comment by swmuir** [comment]
The issue is the name space (prefix) in the file ( ihe: )  the parse is not recovering from not finding it available - i removed the name space 
[nonms.zip](https://github.com/MDMI/mdmiecore/files/1939425/nonms.zip)

the name space provides the ability to avoid element name collision as well as supporting xsi type extensions 

try importing using the attached xml

**Comment by mryanlord** [comment]
namespace issue noted and hopefully remembered
