### ISSUE TITLE
Known UI Bug re: annotating inheritances (?) 

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#69]
Cannot map data elements in ProcedureActivityProcedure dependency (the thing that is not Association) nested in procedureActvityProcedure2 in MedicalEquipmentSection2. Tried 2 times, restated, nothing showing in UI re: mapping. 
[cdamap (3).zip](https://github.com/MDMI/mdmiecore/files/1510008/cdamap.3.zip)

**Comment by mryanlord** [comment]
CAN map dependencies in FHIR model, see, e.g. US-Core Pract, which I used the dependencies for mapping
[fhirccdamapxml.zip](https://github.com/MDMI/mdmiecore/files/1510211/fhirccdamapxml.zip)
.

**Comment by mryanlord** [comment]
ResultsSection2 resultOrganizer2 entry does not have any data elements beyond effectiveTime; mappings to ResultOrganizer (dependency? substituion?) do not show in UI. or in map.  Tried mapping ResultOrganizerID with no success.
[Issue69dec08.zip](https://github.com/MDMI/mdmiecore/files/1543389/Issue69dec08.zip)

**Comment by mryanlord** [comment]
Last attempt with ResultOrganizerID did not show in annotation UI (properties window in MDMI view).

**Comment by swmuir** [comment]
This is an issue in the UI - which will attempt to fix but there is a workaround
The issue appears to be limited to mapping first level associations within the section - in this case ResultOrganizer2 - using(navigating to) inherited properties versus owned properties - The bug is when walking the association path back up the UI  - it stops in this case as the ResultOrganizer and applying the mapping there versus going to the ResultSection2;  I have looked at it and can duplicate  but no easy fix yet

in the meantime,  if you highlight  the ResultOrganizer2 class definition in the editor, right click and select Open Sub Class Editor and select the elements not mapping - in this case id hit okay; then you can go back into the section and map the new property under resultorganizer2 

If you have any issues or questions let me know or send me the current ones causing the issue and i can quickly modify the model

**Comment by mryanlord** [comment]
Workaround does not seem effective in FHIR-CCDA model. Tried using Sub Class Editor to map attributes for Data Enterer, but Sub Class Editor does not provide checkbox for elements not mapping (inheritances from Practitioner base class under the "valueReference" class. Picture attached. 
![subclasseditor](https://user-images.githubusercontent.com/19562254/35195266-e9a30b1e-fe8e-11e7-8ac5-199721ad836a.png)

**Comment by mryanlord** [comment]
known, same as #76; keeping that open
