### ISSUE TITLE
CDA Medications ISO Testing

### ISSUE THREAD

**Issue by swmuir** [MDMI/mdmiecore#84]
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/precondition[not(@nullFlavor)]/criterion[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.25')]]Precondition78.Text342.MedicationAdministrationPreconditionNotes
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.20')]]MedicationActivity25.Text340.MedicationAdministrationInstructionNotes
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.123')]]/participant[not(@nullFlavor)]PSN
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.123')]]/participant[not(@nullFlavor)]ASSIGNED

**Comment by mryanlord** [comment]
annotations and mapping reveal no patent problem. added container at instruction entry. did uml to mdmi transform, isosemantic transform and continued to get error, but with MedicationAdministrationReactionNotes instead of MedicationAdministrationPreconditionNotes

[INFO] Execute ISOSemantic 
[INFO] Create Source Model 
[INFO] Execute processConversions 
[INFO] Execute processOutboundTargetMessage
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/observation[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.9')]]MedicationActivity25.Text333.MedicationAdministrationReactionNotes
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.20')]]MedicationActivity25.Text330.MedicationAdministrationInstructionNotes
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.123')]]/participant[not(@nullFlavor)]ASSIGNED
[ERROR] NODE/VALUE TYPE MISMATCH ClinicalDocument/component/structuredBody/component/section[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.2.1' or @root='2.16.840.1.113883.10.20.22.2.1.1')]]/entry/substanceAdministration[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.16')]]/entryRelationship/act[not(@nullFlavor) and templateId[(@root='2.16.840.1.113883.10.20.22.4.123')]]/participant[not(@nullFlavor)]PSN
[ERROR] Semantic Element not Parsed Text330
[INFO] Completed Transformation

**Comment by swmuir** [comment]
Fixed
